resources:
# Firewall rules
- name: hc-firewall-django
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/paginanominaciones/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges: 
    - 0.0.0.0/0
    targetTags:
    - hc-django
    allowed:
    - IPProtocol: TCP
      ports: 
      - 8080

- name: hc-firewall-db
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/paginanominaciones/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceTags: 
    - hc-django
    targetTags:
    - hc-db
    allowed:
    - IPProtocol: TCP
      ports: 
      - 5432

# Database instance
- name: hc-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/paginanominaciones/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/paginanominaciones/global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - hc-db
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update
          apt-get install -y postgresql postgresql-contrib
          sudo -u postgres psql -c "CREATE USER historiasclinicas_user WITH PASSWORD 'isis2503';"
          sudo -u postgres createdb -O historiasclinicas_user historiasclinicas_db
          echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/*/main/pg_hba.conf
          echo "listen_addresses='*'" >> /etc/postgresql/*/main/postgresql.conf
          echo "max_connections=2000" >> /etc/postgresql/*/main/postgresql.conf
          systemctl restart postgresql

# Django instance
- name: hc-django
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/paginanominaciones/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/paginanominaciones/global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - hc-django
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update
          apt-get install -y python3-pip git
          mkdir -p /labs
          cd /labs
          git clone https://github.com/Angelokc01/historiasClinicas.git
          cd historiasClinicas
          pip3 install -r requirements.txt
          python3 manage.py makemigrations
          python3 manage.py migrate
